version: '3.7'
services:

  sites-proxy:
    image: fromdoppler/sites-proxy:local
    deploy:
      replicas: 1
  
  doppler-webapp:
    deploy:
      replicas: 1

  doppler-docker-playground:
    deploy:
      replicas: 1

  doppler-forms:
    deploy:
      replicas: 1
