version: '3.7'
services:

  sites-proxy:
    image: fromdoppler/sites-proxy:v0
    depends_on: 
      - doppler-webapp
      - doppler-docker-playground
      - doppler-forms
    networks:
      - sites
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        condition: on-failure
    secrets:
      - site.crt
      - site.key
  
  doppler-webapp:
    image: fromdoppler/doppler-webapp:production-v1
    networks:
      - sites
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        condition: on-failure

  doppler-docker-playground:
    image: fromdoppler/doppler-docker-playground:v0
    secrets:
      - source: AnotherSecretSetting
        target: PlaygroundSettings__AnotherSecretSetting
      - source: doppler-docker-playground_appsettings.Secret.json
        target: appsettings.Secret.json
    networks:
      - sites
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        condition: on-failure

  doppler-forms:
    image: fromdoppler/doppler-forms:v0
    secrets:
      - source: doppler-forms_appsettings.Secret.json
        target: appsettings.Secret.json
      - EncryptionSettings__InitVectorAsAsciiString
      - EncryptionSettings__SaltValueAsAsciiString
      - EncryptionSettings__Password
    networks:
      - sites
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        condition: on-failure

networks:
  sites:
    external: false

secrets:
  AnotherSecretSetting:
    file: ./secrets/AnotherSecretSetting
  doppler-docker-playground_appsettings.Secret.json:
    file: ./secrets/doppler-docker-playground/appsettings.Secret.json
  doppler-forms_appsettings.Secret.json:
    file: ./secrets/doppler-forms/appsettings.Secret.json
  EncryptionSettings__InitVectorAsAsciiString:
    file: ./secrets/EncryptionSettings/InitVectorAsAsciiString
  EncryptionSettings__SaltValueAsAsciiString:
    file: ./secrets/EncryptionSettings/SaltValueAsAsciiString
  EncryptionSettings__Password:
    file: ./secrets/EncryptionSettings/Password
  site.crt:
    file: ./secrets/site.crt
  site.key:
    file: ./secrets/site.key